CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO matais_database;

-- Drop existing tables if they exist
DROP TABLE IF EXISTS public.sheetmusic;
DROP TABLE IF EXISTS public.comment;
DROP TABLE IF EXISTS public.blogp;
DROP TABLE IF EXISTS public.account;
DROP TABLE IF EXISTS public.classification;

-- Now recreate all tables

-- Table structure for table `classification`
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table `account`
CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING(50) NOT NULL,
    account_lastname CHARACTER VARYING(50) NOT NULL,
    email CHARACTER VARYING(100) NOT NULL UNIQUE,
    password_hash CHARACTER VARYING(255) NOT NULL,
    account_type VARCHAR(10) NOT NULL CHECK (account_type IN ('client', 'employee', 'admin')),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Table structure for table `blogp`
CREATE TABLE public.blogp (
    bp_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    post_date timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT blogp_pkey PRIMARY KEY (bp_id),
    CONSTRAINT blogp_fk FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Table structure for table `comment`
CREATE TABLE public.comment (
    comment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    bp_id integer NOT NULL,
    account_id integer NOT NULL,
    comment_text text COLLATE pg_catalog."default" NOT NULL,
    comment_date timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT comment_pkey PRIMARY KEY (comment_id),
    CONSTRAINT comment_fk1 FOREIGN KEY (bp_id)
        REFERENCES public.blogp (bp_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT comment_fk2 FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Table structure for table `sheetmusic`
CREATE TABLE public.sheetmusic (
    sm_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sm_year character(4) NOT NULL, 
    sm_description text NOT NULL, 
    sm_image character varying NOT NULL, 
    sm_thumbnail character varying NOT NULL, 
    sm_price numeric(9, 2) NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT sheetmusic_pkey PRIMARY KEY (sm_id),
    CONSTRAINT sheetmusic_fk FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);